const cp = Float32(1005)         # Specific heat capacity of air (J/K/kg)
const eps_fsm = Float32(0.622)       # Ratio of molecular weights of water and dry air
const e0 = Float32(610.78)       # Saturation vapour pressure at Tm (Pa)
const grav = Float32(9.81)       # Acceleration due to gravity (m/s^2)
const hcap_ice = Float32(2100)   # Specific heat capacity of ice (J/K/kg)
const hcap_wat = Float32(4180)   # Specific heat capacity of water (J/K/kg)
const hcon_air = Float32(0.025)  # Thermal conductivity of air (W/m/K)
const hcon_clay = Float32(1.16)  # Thermal conductivity of clay (W/m/K)
const hcon_ice = Float32(2.24)   # Thermal conducivity of ice (W/m/K)
const hcon_sand = Float32(1.57)  # Thermal conductivity of sand (W/m/K)
const hcon_wat = Float32(0.56)   # Thermal conductivity of water (W/m/K)
const I0 = Float32(1367)         # Solar constant (W/m^2)
const Lf = Float32(0.334e6)      # Latent heat of fusion (J/kg)
const Lv = Float32(2.501e6)      # Latent heat of vapourisation (J/kg)
const Ls = Float32(Lf + Lv)      # Latent heat of sublimation (J/kg)
const pi = Float32(3.14159)      # pi
const Rair = Float32(287)        # Gas constant for air (J/K/kg)
const Rwat = Float32(462)        # Gas constant for water vapour (J/K/kg)
const rho_ice = Float32(917)     # Density of ice (kg/m^3)
const rho_wat = Float32(1000)    # Density of water (kg/m^3)
const sb = Float32(5.67e-8)      # Stefan-Boltzmann constant (W/m^2/K^4)
const em_snow = Float32(0.99)    # Emissivity snow for Stefan-Boltzmann
const em_soil = Float32(0.90)    # Emissivity soil for Stefan-Boltzmann
const Tm = Float32(273.15)       # Melting point (K)
const vkman = Float32(0.4)       # Von Karman constant